version: "3.3"
services:
  database:
    image: "mongo"
    container_name: "bitirme_mongo"
    environment:
      MONGO_INITDB_DATABASE: bitirme
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: bitirme
    volumes:
    ## ro stands for read-only
    - ./init_mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    - ./mongo_volume:/data/db
    ports:
      - '27017-27019:27017-27019'
